services:
  _defaults:
    autowire: true
    autoconfigure: true

  External\ContaoSplideBundle\Utils\SplideRenderer:
    public: true

  external_packages.contao_splide.renderer:
    alias: External\ContaoSplideBundle\Utils\SplideRenderer
    public: true
